// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/Serares/ssr/admin/types"
import "fmt"

func Submit(contents types.BasicIncludes, submitIncludes types.SubmitIncludes, props types.SubmitProps) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><span><link rel=\"stylesheet\" href=\"https://unpkg.com/dropzone@5/dist/min/dropzone.min.css\" type=\"text/css\"><link rel=\"stylesheet\" href=\"https://unpkg.com/leaflet@1.6.0/dist/leaflet.css\" integrity=\"sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==\" crossorigin=\"\"><script src=\"https://unpkg.com/leaflet@1.6.0/dist/leaflet.js\" integrity=\"sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew==\" crossorigin=\"\"></script><style>\n\t\t\t\t#mapid {\n\t\t\t\t\tmin-height: 400px;\n\t\t\t\t}\n\t\t\t</style></span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = contents.Header.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<body class=\"page-load\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = contents.Preload.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Wrapper Start --><div id=\"page_wrapper\" class=\"container-fluid\"><div class=\"row\"><header id=\"header\" class=\"w-100 bg_white nav-on-top\"><!-- Nav Header Start -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = contents.Navbar.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Nav Header End --></header><!-- Banner Section Start -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = contents.BannerSection.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Banner Section End --><!-- Submit Property Start --><section id=\"submit_property\" class=\"full_row py_80 bg_gray\"><div class=\"container\"><div class=\"row\"><div class=\"col-lg-9 col-md-10\"><form id=\"upload-form\" action=\"/submit\" method=\"POST\" class=\"dropzone\" enctype=\"multipart/form-data\"><div class=\"basic_information\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.ErrorMessage != "" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"text-danger bold\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(props.ErrorMessage)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/submit.templ`, Line: 44, Col: 62}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if props.SuccessMessage != "" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"text-success bold\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.SuccessMessage)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/submit.templ`, Line: 46, Col: 65}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h4 class=\"inner-title mb-4\">Basic Information</h4><div class=\"row\"><div class=\"col-md-12 col-sm-12\"><div class=\"form-group\"><input value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(props.Property.Title))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" name=\"title\" type=\"text\" placeholder=\"Property Title\" class=\"form-control\"></div></div><div class=\"col-md-6 col-sm-12\"><label>Tipul proprietatii</label> <select name=\"property_type\" class=\"form-control\" data-live-search=\"true\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, option := range props.PropertyTypes {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(option.Value))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if option.Value == props.Property.PropertyType {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" selected=\"true\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(option.DisplayName)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/submit.templ`, Line: 65, Col: 36}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</select></div><div class=\"col-md-6 col-sm-6\"><div class=\"form-group\"><label>Tranzactie</label> <select name=\"property_transaction\" class=\"form-control\" data-live-search=\"true\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, option := range props.PropertyTransaction {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<option value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(option.Value))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if option.Value == props.Property.PropertyTransaction {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" selected=\"true\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(option.DisplayName)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/submit.templ`, Line: 81, Col: 37}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</select></div></div><div class=\"col-md-6 col-sm-6\"><div class=\"form-group\"><label for=\"price\">Pretul:</label> <input value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", props.Property.Price)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" name=\"price\" type=\"number\" placeholder=\"Pretul\" class=\"form-control\"></div></div><div class=\"col-md-4 col-sm-4\"><div class=\"form-group\"><ul class=\"check_submit\"><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.Property.IsFeatured == 1 {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"is_featured\" id=\"is_featured\" class=\"hide\" type=\"checkbox\"> <label for=\"is_featured\">Apare pe pagina principala:</label></li></ul></div></div><div class=\"col-md-4 col-sm-4\"><div class=\"form-group\"><label for=\"property_surface\">Suprafata m²</label> <input value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(fmt.Sprintf("%d", props.Property.PropertySurface)))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" name=\"property_surface\" type=\"number\" placeholder=\"Suprafata m²\" class=\"form-control\"></div></div></div><div class=\"alert alert-warning\">Please input the correct information of your property. Because it will effect on property search.</div></div><div class=\"description mt-5\"><h4 class=\"inner-title mb-4\">Descriere</h4><div class=\"form-group\"><textarea name=\"property_description\" placeholder=\"Type Description...\" class=\"form-control\" rows=\"5\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(props.Property.PropertyDescription)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/submit.templ`, Line: 158, Col: 150}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</textarea></div><div class=\"alert alert-warning\">Need a proper description about the property. So that client can easily understand about the property.</div></div><div class=\"property_location mt-5\"><h4 class=\"inner-title mb-4\">Adresa</h4><div class=\"form-group\"><textarea name=\"property_address\" placeholder=\"Adresa\" class=\"form-control\" rows=\"5\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(props.Property.PropertyAddress)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/submit.templ`, Line: 165, Col: 129}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</textarea></div></div><div class=\"energy_certificate mt-5\"><h4 class=\"inner-title mb-4\">Certificat energetic</h4><div class=\"form-group\"><select name=\"energy_class\" class=\"form-control\" data-live-search=\"true\"><option")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.EnergyClass == "A" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" selected=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" value=\"A\">A</option> <option")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.EnergyClass == "B" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" selected=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" value=\"B\">B</option></select><br><div class=\"mt-3\"><input value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(props.PropertyFeatures.EnergyConsumptionPrimary))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" name=\"energy_consumption_primary\" type=\"text\" placeholder=\"Consum de energie primara\" class=\"form-control\"> <input value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(props.PropertyFeatures.EnergyEmissionsIndex))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" name=\"energy_emissions_index\" type=\"text\" placeholder=\"Indice emisii CO2:\" class=\"form-control\"> <input value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(props.PropertyFeatures.EnergyConsumptionGreen))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" name=\"energy_consumption_green\" type=\"text\" placeholder=\"Consum total specific de energie din surse regenerabile\" class=\"form-control\"></div></div><div class=\"alert alert-warning\">Need a proper description about the property. So that client can easily understand about the property.</div></div><div class=\"destination mt-5\"><h4 class=\"inner-title mb-4\">Destinatie</h4><div class=\"form-group\"><ul class=\"check_submit\"><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.DestinationResidential {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"destination_residential\" id=\"destination_residential\" class=\"hide\" type=\"checkbox\"> <label for=\"destination_residential\">rezidential</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.DestinationCommercial {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"destination_commercial\" id=\"destination_commercial\" class=\"hide\" type=\"checkbox\"> <label for=\"destination_commercial\">comercial</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.DestinationOffice {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"destination_office\" id=\"destination_office\" class=\"hide\" type=\"checkbox\"> <label for=\"destination_office\">birou</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.DestinationHoliday {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"destination_holiday\" id=\"destination_holiday\" class=\"hide\" type=\"checkbox\"> <label for=\"destination_holiday\">Vacanta</label></li></ul></div></div><div class=\"other mt-5\"><h4 class=\"inner-title mb-4\">Alte spatii utile</h4><div class=\"form-group\"><ul class=\"check_submit\"><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.OtherUtilitiesTerrance {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"other_utilities_terrance\" id=\"other_utilities_terrance\" class=\"hide\" type=\"checkbox\"> <label for=\"other_utilities_terrance\">Terasa</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.OtherUtilitiesServiceToilet {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"other_utilities_service_toilet\" id=\"other_utilities_service_toilet\" class=\"hide\" type=\"checkbox\"> <label for=\"other_utilities_service_toilet\">WC SERVICIU</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.OtherUtilitiesUndergroundStorage {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"other_utilities_underground_storage\" id=\"other_utilities_underground_storage\" class=\"hide\" type=\"checkbox\"> <label for=\"other_utilities_underground_storage\">Boxa la subsol</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.OtherUtilitiesStorage {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"other_utilities_storage\" id=\"other_utilities_storage\" class=\"hide\" type=\"checkbox\"> <label for=\"other_utilities_storage\">Debara</label></li></ul></div></div><div class=\"furnished mt-5\"><h4 class=\"inner-title mb-4\">Mobilat</h4><div class=\"form-group\"><ul class=\"check_submit\"><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.FurnishedNot {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"furnished_not\" id=\"furnished_not\" class=\"hide\" type=\"checkbox\"> <label for=\"furnished_not\">Nemobilat</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.FurnishedPartially {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"furnished_partially\" id=\"furnished_partially\" class=\"hide\" type=\"checkbox\"> <label for=\"furnished_partially\">Partial</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.FurnishedComplete {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"furnished_complete\" id=\"furnished_complete\" class=\"hide\" type=\"checkbox\"> <label for=\"furnished_complete\">Complet</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.FurnishedLuxury {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"furnished_luxury\" id=\"furnished_luxury\" class=\"hide\" type=\"checkbox\"> <label for=\"furnished_luxury\">Lux</label></li></ul></div></div><div class=\"interior mt-5\"><h4 class=\"inner-title mb-4\">Stare interior</h4><div class=\"form-group\"><ul class=\"check_submit\"><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.InteriorNeedsRenovation {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"interior_needs_renovation\" id=\"interior_needs_renovation\" class=\"hide\" type=\"checkbox\"> <label for=\"interior_needs_renovation\">Necesita renovare</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.InteriorHasRenovation {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"interior_has_renovation\" id=\"interior_has_renovation\" class=\"hide\" type=\"checkbox\"> <label for=\"interior_has_renovation\">Renovat</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.InteriorGoodState {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"interior_good_state\" id=\"interior_good_state\" class=\"hide\" type=\"checkbox\"> <label for=\"interior_good_state\">Buna</label></li></ul></div></div><div class=\"heating mt-5\"><h4 class=\"inner-title mb-4\">Sistem incalzire</h4><div class=\"row\"><ul class=\"check_submit\"><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.HeatingTermoficare {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"heating_termoficare\" id=\"heating_termoficare\" class=\"hide\" type=\"checkbox\"> <label for=\"heating_termoficare\">Termoficare</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.HeatingCentralHeating {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"heating_central_heating\" id=\"heating_central_heating\" class=\"hide\" type=\"checkbox\"> <label for=\"heating_central_heating\">Centrala proprie</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.HeatingBuilding {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"heating_building\" id=\"heating_building\" class=\"hide\" type=\"checkbox\"> <label for=\"heating_building\">Centrala imobil</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.HeatingStove {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"heating_stove\" id=\"heating_stove\" class=\"hide\" type=\"checkbox\"> <label for=\"heating_stove\">Soba/Teracota</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.HeatingRadiator {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"heating_radiator\" id=\"heating_radiator\" class=\"hide\" type=\"checkbox\"> <label for=\"heating_radiator\">Calorifer</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.HeatingOtherElectrical {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"heating_other_electrical\" id=\"heating_other_electrical\" class=\"hide\" type=\"checkbox\"> <label for=\"heating_other_electrical\">Alte metode electrice:</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.HeatingGasConvector {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"heating_gas_convector\" id=\"heating_gas_convector\" class=\"hide\" type=\"checkbox\"> <label for=\"heating_gas_convector\">Convector gaz</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.HeatingInfraredPanels {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"heating_infrared_panels\" id=\"heating_infrared_panels\" class=\"hide\" type=\"checkbox\"> <label for=\"heating_infrared_panels\">Panouri infrarosu</label></li><li><input")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if props.PropertyFeatures.HeatingFloorHeating {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" checked=\"true\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" name=\"heating_floor_heating\" id=\"heating_floor_heating\" class=\"hide\" type=\"checkbox\"> <label for=\"heating_floor_heating\">Incalzire prin pardoseala</label></li></ul></div><div class=\"alert alert-warning\">Check the extra features and facility of the property, it will show with the property.</div></div><div class=\"upload_media mt-5\"><h4 class=\"inner-title mb-4\">Images</h4><p></p><div class=\"row\"><div class=\"col-md-12\"><div id=\"images-input\" class=\"browse_submit\"><span>Add Photos</span><div class=\"dz-default dz-message\"><label class=\"dz-button fileupload_label specific extra\">Click here to add images</label></div></div></div><div class=\"col-lg-12\"><div class=\"property_thumbnails mt-5\"><div class=\"row dropzone-previews\"></div></div></div></div><div class=\"alert alert-warning\">Try uploading wide resolution format for images The first images uploaded will be selected as the thumbnail</div></div><div class=\"single_map mb-5\"><h4 class=\"inner-title mb-4\">Locație</h4><div id=\"mapid\" class=\"map-canvas\"></div></div><input type=\"text\" id=\"latitude\" name=\"latitude\" class=\"hidden\" style=\"visibility: hidden;\"> <input type=\"text\" id=\"longitude\" name=\"longitude\" class=\"hidden\" style=\"visibility: hidden;\"><div class=\"browse_submit\"><button type=\"submit\" name=\"submit\" class=\"btn btn_primary\">Adauga</button></div></form></div></div></div></section><!-- Submit Property End --><!-- Footer Section Start -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = contents.Footer.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Footer Section End --><!-- Find Part Satrt --><a href=\"#\" id=\"scroll\"><i class=\"fas fa-arrow-up\"></i></a><!-- Find Part Satrt --></div></div><!-- Wrapper End --><script src=\"https://unpkg.com/dropzone@5/dist/min/dropzone.min.js\"></script><script src=\"/assets/js/custom/handle_presign.js\"></script><script src=\"/assets/js/custom/dropzone_submit_external.js\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = contents.Scripts.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = submitIncludes.SubmitDropzoneScript.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = submitIncludes.Modal.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = submitIncludes.LeafletMap.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
