// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package includes

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func DropzoneEdit(imagesPaths []string, url string, deleteImagesFormKey string, imagesFormKey string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_DropzoneEdit_b58b`,
		Function: `function __templ_DropzoneEdit_b58b(imagesPaths, url, deleteImagesFormKey, imagesFormKey){InitEditDropzone(imagesPaths, url, deleteImagesFormKey, imagesFormKey)
}`,
		Call:       templ.SafeScript(`__templ_DropzoneEdit_b58b`, imagesPaths, url, deleteImagesFormKey, imagesFormKey),
		CallInline: templ.SafeScriptInline(`__templ_DropzoneEdit_b58b`, imagesPaths, url, deleteImagesFormKey, imagesFormKey),
	}
}
