// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package includes

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func DropzoneSubmit(imagesFormKey string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_DropzoneSubmit_1696`,
		Function: `function __templ_DropzoneSubmit_1696(imagesFormKey){InitSubmitDropzone(imagesFormKey)
}`,
		Call:       templ.SafeScript(`__templ_DropzoneSubmit_1696`, imagesFormKey),
		CallInline: templ.SafeScriptInline(`__templ_DropzoneSubmit_1696`, imagesFormKey),
	}
}
