// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.476
package includes

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func LeafletMap(lat string, lng string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_LeafletMap_a6d2`,
		Function: `function __templ_LeafletMap_a6d2(lat, lng){function BuildLeafletMap(lat, lng, mapId) {
        this.mapId = mapId;
        this.lat = +lat;
        this.lng = +lng;
        this.zoomLevel = 15;
        this.mapElement;
        this.initMap();
        this.marker;
    }   

    BuildLeafletMap.prototype.initMap = function () {
        try {
            this.mapElement = L.map(this.mapId).setView([this.lat, this.lng], this.zoomLevel);
            this.addTileLayer();
            this.setMarker();
            this.mapElement.on('click', this.onClick.bind(this));
        } catch (err) {
            this.handleError(err);
        }
    }

    BuildLeafletMap.prototype.onClick = function(e) {
        document.getElementById('latitude').value = e.latlng.lat;
        document.getElementById('longitude').value = e.latlng.lng;
        this.lat = e.latlng.lat;
        this.lng = e.latlng.lng;
        if (this.marker) {
            this.mapElement.removeLayer(this.marker);
        }
        this.setMarker();
    }

    BuildLeafletMap.prototype.addTileLayer = function () {
        L.tileLayer('https://api.mapbox.com/styles/v1/empten/ck9qwupj76bgi1ipde38gjsmg/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoiZW1wdGVuIiwiYSI6ImNrOXF3eWh0azBvbXkzbHFjMWNoY2x1NzIifQ.xolL5C6kDqZvZzRFoCmdMg', {
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            maxZoom: 18,
            id: 'mapbox/streets-v11',
            tileSize: 512,
            zoomOffset: -1,
            accessToken: 'pk.eyJ1IjoiZW1wdGVuIiwiYSI6ImNrOXF3eWh0azBvbXkzbHFjMWNoY2x1NzIifQ.xolL5C6kDqZvZzRFoCmdMg'
        }).addTo(this.mapElement);
    }

    BuildLeafletMap.prototype.handleError = function (err) {
        console.log("No map in here", err);
    }

    BuildLeafletMap.prototype.setMarker = function () {
        this.marker = L.marker([this.lat, this.lng]).addTo(this.mapElement);
    }

    var mapId = "mapid";
    var leaflet_map = new BuildLeafletMap(lat, lng, mapId);}`,
		Call:       templ.SafeScript(`__templ_LeafletMap_a6d2`, lat, lng),
		CallInline: templ.SafeScriptInline(`__templ_LeafletMap_a6d2`, lat, lng),
	}
}
