// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package lite

import (
	"time"
)

type Property struct {
	ID                               string
	Humanreadableid                  string
	CreatedAt                        time.Time
	UpdatedAt                        time.Time
	Title                            string
	Floor                            int64
	UserID                           string
	Images                           string
	Thumbnail                        string
	IsFeatured                       int64
	EnergyClass                      string
	EnergyConsumptionPrimary         string
	EnergyEmissionsIndex             string
	EnergyConsumptionGreen           string
	DestinationResidential           int64
	DestinationCommercial            int64
	DestinationOffice                int64
	DestinationHoliday               int64
	OtherUtilitiesTerrance           int64
	OtherUtilitiesServiceToilet      int64
	OtherUtilitiesUndergroundStorage int64
	OtherUtilitiesStorage            int64
	PropertyTransaction              string
	PropertyType                     string
	PropertyAddress                  string
	PropertySurface                  int64
	PropertyDescription              string
	Price                            int64
	FurnishedNot                     int64
	FurnishedPartially               int64
	FurnishedComplete                int64
	FurnishedLuxury                  int64
	InteriorNeedsRenovation          int64
	InteriorHasRenovation            int64
	InteriorGoodState                int64
	HeatingTermoficare               int64
	HeatingCentralHeating            int64
	HeatingBuilding                  int64
	HeatingStove                     int64
	HeatingRadiator                  int64
	HeatingOtherElectrical           int64
	HeatingGasConvector              int64
	HeatingInfraredPanels            int64
	HeatingFloorHeating              int64
}

type User struct {
	ID           string
	CreatedAt    time.Time
	Isadmin      bool
	Issu         bool
	Email        string
	Passwordhash string
}
