// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: properties.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addProperty = `-- name: AddProperty :exec
INSERT INTO properties(
        id,
        created_at,
        updated_at,
        title,
        floor,
        published_at,
        user_id
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type AddPropertyParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Floor       int32
	PublishedAt time.Time
	UserID      uuid.UUID
}

func (q *Queries) AddProperty(ctx context.Context, arg AddPropertyParams) error {
	_, err := q.db.ExecContext(ctx, addProperty,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Floor,
		arg.PublishedAt,
		arg.UserID,
	)
	return err
}
