// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/Serares/ssr/homepage/types"

func Contact(contents types.BasicIncludes) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html lang=\"en\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = contents.Header.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<link rel=\"stylesheet\" href=\"/assets/css/contact.css\"><body class=\"page-load\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = contents.Preload.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Wrapper Start --><div id=\"page_wrapper\" class=\"container-fluid\"><div class=\"row\"><header id=\"header\" class=\"w-100 bg_white nav-on-top\"><!-- Nav Header Start -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = contents.Navbar.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Nav Header End --></header><!-- Banner Section Start --><!-- <%- include('../../includes/banner_section.ejs', {pageTitle: pageTitle, imageUrl:imageUrl}) %> --><!-- Banner Section End --><!-- Contact Section Start --><section id=\"contact\" class=\"py_80 bg_gray full_row\"><div class=\"container\"><h2 class=\"mb-4\">TRIMITE-NE <span class=\"text_primary\">UN MESAJ</span></h2><div class=\"row\"><div class=\"col-md-6\"><div class=\"contact_area\"><p>Incercăm să răspundem cât mai repede posibil</p><form id=\"contact-form\" class=\"contact_message mt_30\"><div class=\"row\"><div class=\"form-group col-md-6 col-sm-6\"><input class=\"form-control\" id=\"firstname\" type=\"text\" name=\"firstname\" placeholder=\"Prenume\"></div><div class=\"form-group col-md-6 col-sm-6\"><input class=\"form-control\" id=\"lastname\" type=\"text\" name=\"lastname\" placeholder=\"Nume\"></div><div class=\"form-group col-md-6 col-sm-6\"><input class=\"form-control\" id=\"email\" type=\"text\" name=\"email\" placeholder=\"Adresa Email\"></div><div class=\"form-group col-md-12 col-sm-12\"><textarea class=\"form-control\" id=\"message\" name=\"message\" placeholder=\"Mesaj\" rows=\"5\"></textarea></div><div class=\"form-group col-md-12 col-sm-12\"><input id=\"send\" class=\"btn btn_primary\" type=\"submit\" value=\"Send\"></div><div class=\"col-md-12\"><div class=\"error-handel\"><div id=\"success\">Mesajul a fost trimis.</div><div id=\"error\">Eroare la procesarea mesajului, te rog incearcă din nou.</div></div></div></div></form></div></div><div class=\"col-md-6\"><div class=\"row\"><div class=\"col-md-6\"><div class=\"contact_right\"><h5 class=\"mb-4\">Informații</h5><p>+40 727 971 584, support@undertown.ro</p></div></div><div class=\"col-md-12\"><div class=\"contact_right\"><div id=\"map\"></div></div></div></div></div></div></div></section><!-- Contact Section End --><!-- Footer Section Start -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = contents.Footer.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Footer Section End --><!-- Find Part Satrt --><a href=\"#\" id=\"scroll\"><i class=\"fas fa-arrow-up\"></i></a><!-- Find Part Satrt --></div></div><!-- Wrapper End -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = contents.Scripts.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
